### ISSUE TITLE
Implement YAML representation for sex-biased admixture 

### ISSUE THREAD

**Issue by sgravel** [sgravel/tracts#36]
We want to add sex-biased admixture capability to tracts, and we will need to generalize the YAML format to handle this.

**Comment by santiago1234** [comment]
# Proposed YAML representation for sex-biased admixture

How users could specify a sex-biased model in *tracts*?
 
We start with a simple model to establish the baseline and then extend it to incorporate sex bias using a `male_to_female_ratio` parameter.

## Simple Model

A basic Tracts YAML model without sex bias.

```yaml
demes:
  - name: EUR
  - name: AFR
  - name: X
      ancestors: [EUR, AFR]
      proportions: [R, 1-R]
      start_time: tx
pulses:
  - sources: [EUR]
    dest: X
    proportions: [P]
    time: tp
migrations:
  - source: EUR
    dest: X
    rate: K
    start_time: tm1
    end_time: tm2
```

## Extending to a Sex-Biased Model

Notes on the Sex-Bias Model

* Each pulse or migration event will include a `male_to_female_ratio` parameter to capture the relative contributions of males and females.
* The male_to_female_ratio ($r$) is defined as: $r = \frac{m}{f}$
* From $r$, the male proportion ($m$) and female proportion ($f$) are calculated as:
  - $$m = \frac{r}{1+r}$$
  - $$f = 1 - m$$

Proposed YAML Syntax

```yaml
demes:
  - name: EUR
  - name: AFR
  - name: X
      ancestors: 
      - EUR
        male_to_female_ratio: mfr_i_eur # We need a male_to_female_ratio for each ancestor
      - AFR
        male_to_female_ratio: mfr_i_afr
      proportions: [R, 1-R]
      start_time: tx
pulses:
  - sources: [EUR]
    dest: X
    proportions: [P]
    time: tp
    male_to_female_ratio: mfr_p  # Male-to-female ratio for this pulse
migrations:
  - source: EUR
    dest: X
    rate: K
    start_time: tm1
    end_time: tm2
    male_to_female_ratio: mfr_m  # Male-to-female ratio for continuous migration
```

As an alternative, we could introduce a global sex_bias parameter, allowing users to specify whether sex bias should be applied at a higher level. When set to true, the male_to_female_ratio would be inferred automatically for all migration, founder, and pulse events, and the output would include the inferred values for the sex_bias terms.

```yaml
demes:
  - name: EUR
  - name: AFR
  - name: X
      ancestors: [EUR, AFR]
      proportions: [R, 1-R]
      start_time: tx
pulses:
  - sources: [EUR]
    dest: X
    proportions: [P]
    time: tp
migrations:
  - source: EUR
    dest: X
    rate: K
    start_time: tm1
    end_time: tm2
sex_bias: True # either True or False
```
Hey @sgravel  and @gonzalez-delgado , here’s a sketch of some alternatives for defining a sex bias model.
